module.exports = {
  SCK_CONFIG_SET_FILENAME: "200",
  SCK_CONFIG_SET_WEBPORT: "201",
  SCK_LOADED_CFG: "101",
  SCK_SERVER_RESTART: "10",
  SCK_UPDATE_DOMAIN: "50",
  SCK_DELETE_DOMAIN: "51",
  SCK_LOADED_DOMAINS: "102",
};
