module.exports = {
  SCK_UPDATE_CONFIG: "52",
  SCK_LOADED_CFG: "101",
  SCK_SERVER_RESTART: "10",
  SCK_UPDATE_DOMAIN: "50",
  SCK_DELETE_DOMAIN: "51",
  SCK_LOADED_DOMAINS: "102",
  SCK_LOADED_WHOIS: "103",
  SCK_WHOIS_CACHE_MISS: "104",
};
